### ISSUE TITLE
Host problem

### ISSUE THREAD

**Issue by IuriAdriel** [nicholas-wilcox/lit-modal-portal#2]
Hi, all good?

I'm using this library in a lit component project and calling the component into a Tauri+React project.

Initially, it works perfectly, but if I change the page and then return, I receive this message in the console:

'**You attempted to attach a singleton controller to more than one host.**'

After that, the modals stop working.

Can you help me? What could be happening?

**Comment by nicholas-wilcox** [comment]
Hello @IuriAdriel, I just wanted to let you know that I've seen this issue and that I hope to have some time to help troubleshoot later this month.

I will say that the error you've reported is something I put in my own code because I'm using a singleton pattern. I don't know much about Tauri (hope to remedy that someday 😄), but I imagine some implicit assumption my code makes about its lifecycle isn't meshing with your application.

**Comment by nicholas-wilcox** [comment]
Hey @IuriAdriel, I've been refactoring this package practically from scratch over the past week. It no longer uses (or even exports) the `<modal-portal>` component or the `modalController`. Instead, the `portal` directive has been simplified and enhanced to support most use cases for portals without the need for a separate component or controller.

If you are still using this library, then I suggest updating to the latest minor version, 0.6. You will most likely need to refactor your code, but the error you ran into definitely won't happen again :).

**Comment by nicholas-wilcox** [comment]
Closing this issue, since the code has been modified such that the error in question doesn't "exist" anymore. If there are still problems getting this package to work with Tauri, then a new issue can be created.
